Ulcers_Server/urls.py
from django.contrib import admin
from django.urls import path
from server.views import *
from Ulcers_Server import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', profile, name="index"),
    path('profile/', profile, name="profileView"),
    path('users/<int:patient_id>', search_users, name="search_users"),
    path('edit/<int:patient_id>', edit_patient, name="edit_patient"),
    path('users/<int:patient_id>/<int:test_id>', search_tests, name="search_tests"),
    path('remove/<int:patient_id>', remove_patient, name="remove_patient"),
    path('remove/<int:patient_id>/<int:test_id>', remove_test, name="remove_test"),
    path('edit/', edit_user, name="edit_user"),
    path('logout/', logout, name="logout"),
    path('create/', create_patient, name="create_patient"),
    path('login/', login_register, name="login_register"),
    path('api/data', recieve_data, name="recieve_data"),
    path('api/login', login_api, name="login_api"),
    url(r'^ajax/analyze_data/$', analyze_data, name='analyze_data'),
    url(r'^ajax/update_data/$', update_data, name='update_data'),
    url(r'^ajax/save_image/$', save_image, name='save_image'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from jsonfield import JSONField

class MediaFileSystemStorage(FileSystemStorage):
    def get_available_name(self, name, max_length=None):
        if max_length and len(name) > max_length:
            raise (Exception("el nombre del fichero es más grande de lo permitido"))
        return name

    def _save(self, name, content):
        if self.exists(name):
            # si ya existe no se guarda
            return name
        # Si el fichero es nuevo se guarda
        return super(MediaFileSystemStorage, self)._save(name, content)

class Doctor(models.Model):
    user = models.OneToOneField(User, auto_created=True, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='', blank=True, default="user.png",
                               storage=MediaFileSystemStorage())
    pin = models.CharField(null=True, max_length=6, blank=True, unique=True)

    def save(self, *args, **kwargs):
        super(Doctor, self).save(*args, **kwargs)
    def __str__(self):
        return self.user.username

class Patient(models.Model):
    name = models.CharField(max_length=20, default="Def name")
    text = models.TextField(default="Def text", blank=True)
    opciones = (("Male", "Male"), ("Female", "Female"), ("Other", "Other"))
    birth_date = models.DateField(blank=True, default="1980-1-1")
    gender = models.CharField(max_length=8, choices=opciones)
    doctor = models.ForeignKey(Doctor, blank=True, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='', blank=True, default="user.png",
                                    storage=MediaFileSystemStorage())
    def __str__(self):
        return self.name

class Test(models.Model):
    date = models.DateTimeField(default=timezone.now)
    gas_sensors = JSONField(null=True, blank=True)
    distance = models.FloatField(blank=True, default=0.0)
    temperature = JSONField(null=True, blank=True)
    camera_kurokesu = models.ImageField(upload_to='tests/', blank=True)    
    camera_rasp = models.ImageField(upload_to='tests/', blank=True)
    thermal_camera = models.ImageField(upload_to='tests/', blank=True)
    patient = models.ForeignKey(Patient, null=True, blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(Doctor, null=True, blank=True, on_delete=models.CASCADE)
    opciones = (("Positive", "Positive"), ("Negative", "Negative"))
    outcome = models.CharField(max_length=10, choices=opciones, default="Negative")
    NumberUlcers = models.CharField(max_length=10, choices=opciones, default="0")
    TissueTypes = models.CharField(max_length=50, choices=opciones, default="None")
    Ruler = models.CharField(max_length=10, choices=opciones, default="No")
    ImageRight = models.CharField(max_length=20, choices=opciones, default="Image")
    ImageLeft = models.CharField(max_length=20, choices=opciones, default="Image")
    Imagetherm = models.CharField(max_length=20, choices=opciones, default="Image")
    Perimeter =  models.CharField(max_length=20, choices=opciones, default="0 mm")
    Area =  models.CharField(max_length=20, choices=opciones, default="0 mm2")
    Granulation =  models.CharField(max_length=20, choices=opciones, default="0 %")
    Slough =  models.CharField(max_length=20, choices=opciones, default="0 %")
    Necrosis =  models.CharField(max_length=20, choices=opciones, default="0 %")
    Segmented_leftImage = models.ImageField(blank=True)
    Segmented_leftImage_g = models.ImageField(blank=True)
    Segmented_leftImage_s = models.ImageField(blank=True)
    Segmented_leftImage_n = models.ImageField(blank=True)
    ulcer_edited_image = models.ImageField(upload_to='edited/', blank=True)
    tissueTypes_edited_image = models.ImageField(upload_to='edited/', blank=True)
    giveDistance_edited_image = models.ImageField(upload_to='edited/', blank=True)
    distance_ulcer = models.CharField(max_length=10, choices=opciones, default="0")
    Pixels_in_UPP = models.CharField(max_length=20, choices=opciones, default="0")
    Pixels_in_g = models.CharField(max_length=20, choices=opciones, default="0")
    Pixels_in_s = models.CharField(max_length=20, choices=opciones, default="0")
    Pixels_in_n = models.CharField(max_length=20, choices=opciones, default="0")

    def __str__(self):
        return str(self.date)

templates/base_site.html
<!DOCTYPE html>
<html lang="en">
{% load i18n %}
{% load static %}
<head>
    {% block head %}
        {% block meta %}
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
            <!-- Meta, title, CSS, favicons, etc. -->
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1">
        {% endblock meta %}

        <title>{% trans "SmartDoc" %} | {% block title %}{% endblock %}</title>

        {% block stylesheets %}
            <!-- Bootstrap -->
            <link href="/static/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
            <!-- Font Awesome -->
            <link href="/static/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
            <!-- NProgress -->
            <link href="/static/vendors/nprogress/nprogress.css" rel="stylesheet">
            <!-- bootstrap-daterangepicker -->
            <link href="/static/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
            <!-- iCheck -->
            <link href="/static/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
            <!-- bootstrap-progressbar -->
            <link href="/static/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
            <!-- JQVMap -->
            <link href="/static/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
        {% endblock stylesheets %}
        <!-- Custom Theme Style -->
        <link href="/static/build/css/custom.min.css" rel="stylesheet">
    {% endblock head %}
</head>

<body class="{% block body_class %}nav-md {% endblock body_class %}">
{% block body %}
    <div class="container body">
        <div class="main_container">

            {% block sidebar %}
                <div class="col-md-3 left_col {% block sidebar_class %} {% endblock sidebar_class %}">
                    {% include "sidebar.html" %}
                </div>
            {% endblock sidebar %}

            {% block top_navigation %}
                <div class="top_nav">
                    {% include "top_navigation.html" %}
                </div>
            {% endblock top_navigation %}

            {% block content %}
                <!-- {{ content }} -->
            {% endblock content %}

            {% block footer %}
                <footer>
                    {% include "footer.html" %}
                </footer>
            {% endblock footer %}
        </div>
    </div>

    {% block javascripts %}
{#        <script src="/static/js/popper.min.js"></script>#}
        <!-- jQuery -->
        <script src="/static/vendors/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="/static/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- FastClick -->
        <script src="/static/vendors/fastclick/lib/fastclick.js"></script>
        <!-- NProgress -->
        <script src="/static/vendors/nprogress/nprogress.js"></script>
        <!-- bootstrap-progressbar -->
        <script src="/static/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
        <!-- iCheck -->
        <script src="/static/vendors/iCheck/icheck.min.js"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="/static/vendors/moment/min/moment.min.js"></script>
        <script src="/static/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
        <!-- bootstrap-wysiwyg -->
        <script src="/static/vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js"></script>
        <script src="/static/vendors/jquery.hotkeys/jquery.hotkeys.js"></script>
        <script src="/static/vendors/google-code-prettify/src/prettify.js"></script>
        <!-- jQuery Tags Input -->
        <script src="/static/vendors/jquery.tagsinput/src/jquery.tagsinput.js"></script>
        <!-- Switchery -->
        <script src="/static/vendors/switchery/dist/switchery.min.js"></script>
        <!-- Select2 -->
        <script src="/static/vendors/select2/dist/js/select2.full.min.js"></script>
        <!-- Parsley -->
        <script src="/static/vendors/parsleyjs/dist/parsley.min.js"></script>
        <!-- Autosize -->
        <script src="/static/vendors/autosize/dist/autosize.min.js"></script>
        <!-- jQuery autocomplete -->
        <script src="/static/vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js"></script>
        <!-- starrr -->
        <script src="/static/vendors/starrr/dist/starrr.js"></script>
        <!-- Tables -->
        <script src="/static/vendors/datatables.net/js/jquery.dataTables.js"></script>
        <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
        <script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
        <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
        <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
        <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
        <script src="/static/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
        <!-- Chart.js -->
{#        <script src="/static/vendors/Chart.js/dist/Chart.min.js"></script>#}
    {% endblock %}
    <!-- Custom Theme Scripts -->
    <script src="/static/build/js/custom.min.js"></script>
{% endblock body %}
</body>
</html>

templates/create_patient.html
{% extends "base_site.html" %}
{% load i18n %}
{% load static %}


{% block title %}{% trans "Create Patient" %}{% endblock title %}

{% block stylesheets %}
    {{ block.super }}
{% endblock stylesheets %}

{% block content %}
    <div class="right_col" role="main">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                      <h2>{% trans 'Create patient' %}
                          <small></small>
                      </h2>
                    <ul class="nav navbar-right panel_toolbox">
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <br />
                        <form action="{% url "create_patient" %}" enctype="multipart/form-data" method="post" class="form-horizontal form-label-left">{% csrf_token %}
                          <div class="item form-group">
                              <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                     for="id_name">{% trans 'Name' %} <span class="required">*</span>
                                 </label>
                                <div class="col-md-5 col-sm-6 col-xs-12">
                                    <input id="id_name" type="text" name="name" maxlength="100"
                                           class="form-control col-md-7 col-xs-12"
                                           placeholder="{% trans 'Introduce a name' %}" required="required"
                                           data-validate-length-range="2,100"/>
                                </div>
                          </div>
                          <br>

                          <div class="form-group">
                              <label class="control-label col-md-3 col-sm-3 col-xs-12">{% trans 'Gender' %}<span
                                      class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                      <div id="gender" class="btn-group" data-toggle="buttons">
                                        <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                            <input type="radio" name="gender" value="Hombre"><i
                                                class="fa fa-male fa-fw"></i> {% trans 'Male' %}
                                        </label>
                                        <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                            <input type="radio" name="gender" value="Mujer"><i
                                                class="fa fa-female fa-fw"></i> {% trans 'Female' %}
                                        </label>
                                        <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                            <input type="radio" name="gender" value="Other"><i
                                                class="fa fa-cube fa-fw"></i> {% trans 'Other' %}
                                        </label>
                                      </div>
                                </div>
                          </div>
                          <br>

                          <div class="item form-group">
                              <label class="control-label col-md-3 col-sm-3 col-xs-12">{% trans 'Birth date' %}
                                  <span>*</span>
                                 </label>
                                <div class="col-md-1 col-sm-6 col-xs-12">
                                    <input id="id_day" type="text" name="day" maxlength="100"
                                           class="form-control col-md-1 col-xs-12" placeholder="{% trans 'Day' %}"
                                           required="required"/>
                                </div>
                                <div class="col-md-1 col-sm-6 col-xs-12">
                                    <input id="id_month" type="text" name="month" maxlength="100"
                                           class="form-control col-md-1 col-xs-12" placeholder="{% trans 'Month' %}"/>
                                 </div>
                                <div class="col-md-1 col-sm-6 col-xs-12">
                                    <input id="id_year" type="text" name="year" maxlength="100"
                                           class="form-control col-md-1 col-xs-12" placeholder="{% trans 'Year' %}"/>
                                </div>
                          </div>
                          <br>

                          <div class="form-group">
                              <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                     for="id_photo">{% trans 'Photo' %}
                                 </label>
                                <div class="col-md-5 col-sm-6 col-xs-12">
                                        <input id="id_photo" type="file" name="photo"/>
                                </div>
                          </div>
                          <br>

                          <div class="form-group" align="left">
                              <div >
                                  <button type="submit" class="btn btn-success btn-lg"><i class="fa fa-save"></i>
                                      &nbsp; {% trans 'Create' %}</button>
                              </div>
                          </div>

                      </form>
                  </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block javascripts %}

    {{ block.super }}
{% endblock javascripts %}

templates/edit_patient.html
{% extends "base_site.html" %}
{% load i18n %}
{% load static %}


{% block title %}{% trans "Edit User" %}{% endblock title %}

{% block stylesheets %}
    {{ block.super }}
{% endblock stylesheets %}

{% block content %}
    <div class="right_col" role="main">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                      <h2>{% trans 'Modify patient' %}
                          <small></small>
                      </h2>
                    <ul class="nav navbar-right panel_toolbox">
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <br />
                      <form action="{% url "edit_patient" patient_id=patient.id %}" enctype="multipart/form-data" method="post" class="form-horizontal form-label-left">{% csrf_token %}
                          <div class="item form-group">
                              <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                     for="id_name">{% trans 'Name' %} <span class="required">*</span>
                                 </label>
                                <div class="col-md-5 col-sm-6 col-xs-12">
                                    <input id="id_name" type="text" name="name" maxlength="100"
                                           class="form-control col-md-7 col-xs-12"
                                           placeholder="{% trans 'Introduce a name' %}" required="required"
                                           data-validate-length-range="2,100" value="{{ patient.name }}"/>
                                </div>
                          </div>
                          <br>

                          <div class="form-group">
                              <label class="control-label col-md-3 col-sm-3 col-xs-12">{% trans 'Gender' %}<span
                                      class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                      <div id="gender" class="btn-group" data-toggle="buttons">
                                          {% if patient.gender == "Male" %}
                                                <label class="btn btn-default active" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                                    <input type="radio" name="gender" value="Male" checked="checked"><i
                                                        class="fa fa-male fa-fw"></i> {% trans 'Male' %}
                                                </label>
                                                <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                                    <input type="radio" name="gender" value="Female"><i
                                                        class="fa fa-female fa-fw"></i> {% trans 'Female' %}
                                                </label>
                                                <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                                    <input type="radio" name="gender" value="Other"><i
                                                        class="fa fa-cube fa-fw"></i> {% trans 'Other' %}
                                                </label>
                                          {% elif patient.gender == "Female" %}
                                                <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                                    <input type="radio" name="gender" value="Male"><i
                                                        class="fa fa-male fa-fw"></i> {% trans 'Male' %}
                                                </label>
                                                <label class="btn btn-default active" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                                    <input type="radio" name="gender" value="Female" checked="checked"><i
                                                        class="fa fa-female fa-fw"></i> {% trans 'Female' %}
                                                </label>
                                                <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                                    <input type="radio" name="gender" value="Other"><i
                                                        class="fa fa-cube fa-fw"></i> {% trans 'Other' %}
                                                </label>
                                          {% else %}
                                                <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                                    <input type="radio" name="gender" value="Male"><i
                                                        class="fa fa-male fa-fw"></i> {% trans 'Male' %}
                                                </label>
                                                <label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                                    <input type="radio" name="gender" value="Female"><i
                                                        class="fa fa-female fa-fw"></i> {% trans 'Female' %}
                                                </label>
                                                <label class="btn btn-default active" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
                                                    <input type="radio" name="gender" value="Other" checked="checked"><i
                                                        class="fa fa-cube fa-fw"></i> {% trans 'Other' %}
                                                </label>
                                          {% endif %}
                                      </div>
                                </div>
                          </div>
                          <br>

                          <div class="item form-group">
                              <label class="control-label col-md-3 col-sm-3 col-xs-12">{% trans 'Birth date' %}
                                  <span>*</span>
                                 </label>
                                <div class="col-md-1 col-sm-6 col-xs-12">
                                    <input id="id_day" type="text" name="day" maxlength="100"
                                           class="form-control col-md-1 col-xs-12" placeholder="{% trans 'Day' %}"
                                           required="required" value="{{ patient.birth_date.day }}"/>
                                </div>
                                <div class="col-md-1 col-sm-6 col-xs-12">
                                    <input id="id_month" type="text" name="month" maxlength="100"
                                           class="form-control col-md-1 col-xs-12" placeholder="{% trans 'Month' %}"
                                            value="{{ patient.birth_date.month }}"/>
                                 </div>
                                <div class="col-md-1 col-sm-6 col-xs-12">
                                    <input id="id_year" type="text" name="year" maxlength="100"
                                           class="form-control col-md-1 col-xs-12" placeholder="{% trans 'Year' %}"
                                            value="{{ patient.birth_date.year }}"/>
                                </div>
                          </div>
                          <br>

                          <div class="form-group">
                              <label class="control-label col-md-3 col-sm-3 col-xs-12"
                                     for="id_photo">{% trans 'Photo' %}
                                 </label>
                                <div class="col-md-5 col-sm-6 col-xs-12">
                                        <input id="id_photo" type="file" name="photo" value="{{ patient.photo }}"/>
                                </div>
                          </div>
                          <br>

                          <div class="form-group" align="left">
                              <div >
                                  <button type="submit" class="btn btn-success btn-lg"><i class="fa fa-save"></i>
                                      &nbsp; {% trans 'Save' %}</button>
                              </div>
                          </div>

                      </form>
                  </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block javascripts %}

    {{ block.super }}
{% endblock javascripts %}

templates/footer.html
{% load i18n %}
{% load static %}
<div class="pull-right">
    {% trans "Chipmunk - Based on" %}
    <a href="https://github.com/ColorlibHQ/gentelella">Gentelella</a> by <a
        href="https://colorlib.com/">Colorlib</a>
</div>
<div class="clearfix"></div>

templates/index.html
{% extends "base_site.html" %}
{% load i18n %}
{% load static %}


{% block title %}{% trans "Home" %}{% endblock title %}

{% block stylesheets %}
    {{ block.super }}
{% endblock stylesheets %}

{% block content %}
    <div class="right_col" role="main" style="min-height: 936px">

    </div>
{% endblock content %}

{% block javascripts %}

    {{ block.super }}
{% endblock javascripts %}

templates/profile.html
{% extends "base_site.html" %}
{% load i18n %}
{% load static %}


{% block title %}{% trans "Home" %}{% endblock title %}

{% block stylesheets %}
    {{ block.super }}
{% endblock stylesheets %}

{% block content %}
    <div class="right_col" role="main" style="min-height: 936px">
        <div class="col-md-12 col-sm-12 col-xs-12">
{#            <div class="x_panel">#}
            <div class="x_title">
                <h2>{% trans 'Patients' %}
                </h2>
{#              <ul class="nav navbar-right panel_toolbox">#}
{#                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>#}
{#                </li>#}
{#              </ul>#}
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table id="datatable" class="table table-striped table-bordered" style="border-collapse: collapse; border-spacing: 0;">
                <thead>
                  <tr>
                      <th style="">{% trans 'Photo' %}</th>
                      <th>{% trans 'Name' %}</th>
                      <th>{% trans 'Id' %}</th>
                      <th>{% trans 'Delete' %}</th>
                  </tr>
                </thead>
                <tbody>
                    {% for patient in patients %}
                        <tr>
                            <td style="width: 30%"><a href="{% url "search_users" patient_id=patient.id %}"><img src="/images/{{ patient.photo }}" alt="{{ patient.name }}" class="profile_pic"></a></td>
{#                            <td class="profile_pic"><a><img src="/images/{{ patient.photo }}" alt="{{ patient.name }}" class="img-circle profile_pic"></a></td>#}
                            <td>{{ patient.name }}</td>
                            <td>{{ patient.id }}</td>
                            <td><a href="{% url "remove_patient" patient_id=patient.id %}"><i class="glyphicon glyphicon-minus-sign"></i></a></td>
                        </tr>
                    {% endfor %}
                </tbody>
                </table>
            </div>
            </div>
        </div>
{% endblock content %}

{% block javascripts %}

    {{ block.super }}
{% endblock javascripts %}

templates/top_navigation.html
{% load i18n %}
{% load static %}
<div class="nav_menu">
    <nav>
        <div class="nav toggle">
            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
        </div>

        <ul class="nav navbar-nav navbar-right">
            <li class="">
                <a href="javascript:" class="user-profile dropdown-toggle" data-toggle="dropdown"
                   aria-expanded="false">
{#                    <div class="profile_pic">#}
                        <img src="/images/{{ profile.avatar }}" alt="{{ profile.user.username }}" class="img-circle profile_pic">{{ profile.user.username }}
{#                    </div>#}
                    <span class=" fa fa-angle-down"></span>
                </a>
                <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="{% url "profileView" %}"> {% trans "Profile" %}</a></li>
                    <li>
                        <a href="{% url "edit_user" %}">
                            <span>Settings</span>
                        </a>
                    </li>
                    <li><a href="https://github.com/carloslago/Ulcers_Server">{% trans "Help" %}</a></li>
                    <li><a href="{% url "logout" %}"><i class="fa fa-sign-out pull-right"></i>{% trans "Log Out" %}</a></li>
                </ul>
            </li>
        </ul>
    </nav>
</div>